theme: jekyll-theme-cayman
title: Krsna Chandra Musterer
description: Web Developer Seeking Full-time Employment
avatar: https://avatars2.githubusercontent.com/u/23459400?s=400&u=f087a447964e53ef59728861e3de4415104a3007&v=4
footer-links:
  github: krsnachandra
  linkedin: chandra-musterer-01573146
